service: reddit-clone
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  iam:
    role:
      name: reddit-clone-dynamodb
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt postsTable.Arn
            - !GetAtt usersTable.Arn
            - !GetAtt commentsTable.Arn

resources:
  - ${file(serverless-dynamodb.yml)}
  - ${file(serverless-cognito.yml)}

functions:
  - ${file(serverless-go.yml)}

package:
  exclude:
    - .dynamodb/**
    - node_modules/**
    - .gitignore
    - .nvmrc
    - package-lock.json
    - package.json

custom:
  dynamodb:
    stages:
      - dev

plugins:
  - serverless-dynamodb-local
