service: reddit-clone
frameworkVersion: '2 || 3'

provider:
  name: aws

resources:
  - ${file(serverless-dynamodb.yml)}
  - ${file(serverless-cognito.yml)}

custom:
  dynamodb:
    stages:
      - dev

plugins:
  - serverless-dynamodb-local
