// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPost struct {
	Subreddit  string `json:"subreddit"`
	Poster     string `json:"poster"`
	HeaderText string `json:"headerText"`
	SubText    string `json:"subText"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}

type Post struct {
	ID         string `json:"id"`
	Likes      int    `json:"likes"`
	Subreddit  string `json:"subreddit"`
	Poster     string `json:"poster"`
	Timestamp  string `json:"timestamp"`
	HeaderText string `json:"headerText"`
	SubText    string `json:"subText"`
}

type User struct {
	Username string `json:"username"`
	Email    string `json:"email"`
}
